import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

import { themeCssVariables } from "../../src/lib/theme/tokens.js";

const cwd = process.cwd();
const outPath = path.join(cwd, "src", "routes", "styles", "_tokens.css");
const isCheckMode = process.argv.includes("--check");

const header = [
  "/* This file is generated from src/lib/theme/tokens.js. */",
  "/* Do not edit this file directly. */",
  "",
  ":root {",
];

const body = Object.entries(themeCssVariables).map(
  ([name, value]) => `\t--${name}: ${value};`,
);

const footer = ["}", ""];

const nextContent = [...header, ...body, ...footer].join("\n");

const currentContent = await readFile(outPath, "utf8").catch((error) => {
  if (
    error &&
    typeof error === "object" &&
    "code" in error &&
    error.code === "ENOENT"
  ) {
    return null;
  }

  throw error;
});

if (isCheckMode) {
  if (currentContent !== nextContent) {
    console.error("Theme token CSS is out of date. Run `npm run theme:build`.");
    process.exit(1);
  }

  process.exit(0);
}

if (currentContent !== nextContent) {
  await writeFile(outPath, nextContent, "utf8");
}
